name: legalfinder
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  provider: ^6.0.5
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.12.0
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.11
  shared_preferences: ^2.1.1
  fl_chart: ^0.62.0
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.2
  intl: ^0.18.1
  file_picker: ^5.3.1
  carousel_slider: ^4.2.1
  connectivity: ^3.0.6
  connectivity_plus: ^3.0.6
  internet_connection_checker: ^1.0.0+1
  flutter_local_notifications: ^14.1.1
  translator: ^0.1.2
  html_unescape: ^2.0.0




flutter_native_splash:
  color: "
  image: "assets/logo.png"
  android: true
  ios: true


flutter_icons:
  image_path: "assets/logoG.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/


