name: legalfinder
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  provider: ^6.0.5
  flutter_native_splash: ^2.2.0+1
  flutter_launcher_icons: ^0.12.0
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.11
  shared_preferences: ^2.1.1
  fl_chart: ^0.62.0
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.2
  intl: ^0.18.1
  file_picker: ^5.3.1
  carousel_slider: ^4.2.1
  connectivity: ^3.0.6


flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/logoG.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/


